### ISSUE TITLE
想请教下你demo的地址是自己搭的服务器吗？

### ISSUE THREAD

**Issue by guoweiwen** [yatessss/zhihudaily-vue#12]
如题想请教下你demo的地址是自己搭的服务器吗？如果不是，那么你的静态页面是放到哪里去呀？然后nginx的是一个反向代理，那么最终的服务器其实是哪里呀？知乎提供的吗？其实就是一个问题：静态页面放到哪里去？
语言组织能力不怎么好别介意。

**Comment by yatessss** [comment]
不是，是用的github pages，接口是知乎提供的，然后用nginx做了一个反向代理转发了接口就可以了
