### ISSUE TITLE
兄弟 你的demo地址重定向到了一个黄网。。。

### ISSUE THREAD

**Issue by narata** [yatessss/zhihudaily-vue#17]

**Comment by BlBana** [comment]
我刚刚还在工位上，点开给我重定向了，有点尴尬啊 。。。

**Comment by yatessss** [comment]
😂😂域名被回收了  我记得改一下  平时太忙啦


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: xiaosuda <notifications@github.com>
发送时间: 2019年5月17日 16:42
收件人: yatessss/zhihudaily-vue <zhihudaily-vue@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[yatessss/zhihudaily-vue] 兄弟 你的demo地址重定向到了一个黄网。。。 (#17)



好久没维护了，谢谢告知，尽快修复------------------ 原始邮件 ------------------ 
 发件人: "BlBana"<notifications@github.com> 
 发送时间: 2019年5月17日(星期五) 下午4:40 
 收件人: "yatessss/zhihudaily-vue"<zhihudaily-vue@noreply.github.com>; 
 抄送: "Subscribed"<subscribed@noreply.github.com>; 
 主题: Re: [yatessss/zhihudaily-vue] 兄弟 你的demo地址重定向到了一个黄网。。。 (#17) 
 
 
 
 我刚刚还在工位上，点开给我重定向了，有点尴尬啊 。。。 
   
 &mdash;

**Comment by LewisTian** [comment]
> 我刚刚还在工位上，点开给我重定向了，有点尴尬啊 。。。

我也是 233

**Comment by yatessss** [comment]
😂😂委屈各位老铁


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: LewisTian <notifications@github.com>
发送时间: 2019年5月17日 22:14
收件人: yatessss/zhihudaily-vue <zhihudaily-vue@noreply.github.com>
抄送: yatessss <897969073@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[yatessss/zhihudaily-vue] 兄弟 你的demo地址重定向到了一个黄网。。。 (#17)



 
我刚刚还在工位上，点开给我重定向了，有点尴尬啊 。。。
  
我也是 233

**Comment by yatessss** [comment]
已经把链接移除了
