### ISSUE TITLE
vue.http()的方法，post请求参数没有传过去

### ISSUE THREAD

**Issue by tabyouto** [yatessss/zhihudaily-vue#2]
`Vue
    .http({
      url: params.url,
      method: params.method,
      data: params.data || {}
    })`

我参照这种方式写的话，data参数里能接收到对象，但是实际请求没有带参数？不知道是为何

**Comment by yatessss** [comment]
不知道你用的vue resource 是哪个版本， 新版的的API已经有变更了 ，好像没有data字段了  具体的可以去参考文档看一下。

**Comment by tabyouto** [comment]
我用的是0.9.3的版本，还有什么好的方法能把请求的函数再封装一下，在一个文件里写请求路径和方法，使用的过程中只传data数据部分，然后返回的是promise。我看了好几个别人的项目貌似都是在用的地方直接裸用了，感觉不好管理，如果有个统一再封装一下的话，接口返回的错误信息就能集中处理了。。

**Comment by yatessss** [comment]
@tabyouto  额。。。我这样写是其实是觉得这样和原来写jquery感觉差不多，你可以根据自己的具体需求去简单封装一下的~ 每个人对方便的想法也不一样嘛~

**Comment by yatessss** [comment]
@tabyouto  关于版本的问题 看这个文档吧  这个是标准的吧。。。https://github.com/vuejs/vue-resource/blob/master/docs/http.md
