### ISSUE TITLE
图片在本地获取不到（不知道是跨域的问题，还是知乎防盗链）

### ISSUE THREAD

**Issue by liuxsen** [yatessss/zhihudaily-vue#4]
![image](https://cloud.githubusercontent.com/assets/12598696/19410065/062e7a70-9315-11e6-9fff-8c2f2b0dcdaa.png)
我想在本地loalhost:8080 中加载图片地址；可以都没有加载到资源；报错 403；

**Comment by yatessss** [comment]
对，知乎的图片是防盗链的，你可以看一下这样的处理方式： http://www.yatessss.com/2016/07/08/%E4%BD%BF%E7%94%A8vue%E5%AE%8C%E6%88%90%E7%9F%A5%E4%B9%8E%E6%97%A5%E6%8A%A5web%E7%89%88.html   还有一种方式 在issue里能找到，是在img标签中加一个属性的。你可以看下
