### ISSUE TITLE
Access-Control-Allow-Origin:0

### ISSUE THREAD

**Issue by yangpei425** [yatessss/zhihudaily-vue#5]
Access-Control-Allow-Origin:0   Access-Control-Allow-Origin:0    Access-Control-Allow-Origin:0

请开放一下api

**Comment by yatessss** [comment]
不好意思  开放不了   如果本地开发  可以直接请求知乎的接口 配合跨域chrome插件

**Comment by yangpei425** [comment]
没事  ，我用nginx  做了个反向代理。  这几天好好拜读学习下你的代码。

**Comment by yatessss** [comment]
恩 我也是那样的   千万别说拜读。。哈哈哈 好多冗余的
