### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by Huitimkit** [yatessss/zhihudaily-vue#6]
您好，请教一个问题，您是如何实现，从列表页点击某一个选项之后进入详情页，从详情页点击返回，列表页还能定位到上次浏览的位置？

**Comment by yatessss** [comment]
点击的时候会记录scrolltop的值   回到列表页再取这个值

**Comment by Huitimkit** [comment]
@yatessss 那您是怎么实现返回列表的时候，没有再发起请求，我查看您list-default.vue文件中的ready钩子，并没有做什么判断，返回列表的时候却不再发起请求，是怎么实现了组件重新渲染而没有去执行ready钩子？

**Comment by rainbowzx** [comment]
您好  请教一个问题 我引用的的 ajax.js 会报 Cannot read property 'options' of undefined错误

**Comment by yatessss** [comment]
@Huitimkit  keep alive 他不会销毁那个组件的

**Comment by Huitimkit** [comment]
@yatessss 我用了keep alive实现了返回定位到上次浏览的位置，感谢
